### ISSUE TITLE
API authority error: 401 Unauthorized

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2463]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
core services
support-notifications
support-scheduler
device-virtual

### Is this a regression?

 The error happens since March 26

## 🔥 Exception or Error
For example, 
```
12:39:24 ❏ reading
12:39:24 ↳ 41 http://localhost:48080/api/v1/reading
12:39:24   GET https://kong:8443/coredata/api/v1/reading [401 Unauthorized, 242B, 184ms]
12:39:24   1. Status code is 200
12:39:24   ✓  Response time is less than 800ms
```

## 🌍  Your Environment
**Deployment Environment:**
X86 and ARM
**EdgeX Version:**
Master

**Anything else relevant?**
blackbox-testing on Jenkins:
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/DATABASE=mongo,node=centos7-blackbox-4c-2g/20/consoleFull

**Comment by cloudxxx8** [comment]
This issue happens only if the security is enabled.

**Comment by cloudxxx8** [comment]
@tingyuz @bnevis-i do you have any idea about this issue?  thanks.

**Comment by AnthonyMBonafide** [comment]
@tingyuz @mhall119 @bnevis-i This looks like an issue within Kong since `401 Unauthorized` responses are not returned from any of the core-services. Is my assumption correct?

**Comment by bnevis-i** [comment]
@AnthonyMBonafide since there is no security for any microservice other than Vault, my starting assumptuion would be that Kong is returning the 401.  The most likely cause is that the kong token being passed to Kong is invalid somehow.

**Comment by bnevis-i** [comment]
`setupSecurityserviceTest.sh` was broken by the recent conversion of proxy-setup to use go-mod-bootstrap.  Working on a fix.

**Comment by bnevis-i** [comment]
Token parsing fixed in  https://github.com/edgexfoundry/blackbox-testing/pull/419

**Comment by cloudxxx8** [comment]
verified this issue is fixed by edgexfoundry/blackbox-testing#419
@jinlinGuan please help close

**Comment by cloudxxx8** [comment]
@bnevis-i sorry, I verified on the wrong job.  The issues still exists.
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/DATABASE=mongo,node=centos7-blackbox-4c-2g/29/consoleFull

**Comment by bnevis-i** [comment]
Reopened.  Will wait longer.  Jenkins is showing the test ran 11 hours ago... not sure if the fix was commited by the time the test ran.

**Comment by cloudxxx8** [comment]
thanks, @bnevis-i , I can confirm the Jenkins was run after fix merged
@jinlinGuan remind me /bin/security/setupSecurityAccount.sh should also be modified

**Comment by bnevis-i** [comment]
ok.  I'm on it.  Nothing like code duplication to ruin your day.

**Comment by bnevis-i** [comment]
@cloudxxx8 @jinlinGuan Please validate/merge https://github.com/edgexfoundry/blackbox-testing/pull/422.

**Comment by cloudxxx8** [comment]
thanks, @bnevis-i , we eliminated most of the 401 error, but some of them are remained
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/DATABASE=mongo,node=centos7-blackbox-4c-2g/30/consoleFull

**Comment by bnevis-i** [comment]
I'm going to sit on this a day.  I have not been able to reproduce the 401 failures locally.  Let's see what happens tomorrow.

**Comment by cloudxxx8** [comment]
@bnevis-i I just trigger another run, and the remaining error is another issue.  We will investigate them.  Thanks for all the effort you made.  Please feel free to close this issue.
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-security-centos7-blackbox-4c-2g-master/DATABASE=mongo,node=centos7-blackbox-4c-2g/31/consoleFull
