### ISSUE TITLE
PUT requests to /api/v1/event/id/{id} will only update pushed timestamp for event not its readings

### ISSUE THREAD

**Issue by davidmsh** [edgexfoundry/edgex-go#316]
Put method of /api/v1/event/id/{id} behave differently than its Java counterpart  in that it won't update pushed timestamp for readings belong to an event, only the ts on the event itself will be updated. 
markPushed() method in src/main/java/org/edgexfoundry/controller/impl/EventControllerImpl.java will iterate through each reading and update its pushed ts. 
From core-data.raml, it states "Update the event to be pushed" Looks like it will only evnet's pushed ts and it works as designed. Just use this issue to confirm if this is what we want.
From the data model of core data point of view, do we really have cases that readings belonging to an event have different pushed ts than the event ? From current export distro implementation, we export by events, when an event is exported all its readings get exported together. 
Or we want future flexibility that, event may have no pushed ts while each reading has its own ts. If event itself has pushed ts, all its readings can be viewed as having the ts even they do have have pushed field set.

**Comment by yanghua** [comment]
@tsconn23  Can I claim it? Did the California version's branch been cutting?

**Comment by cloudxxx8** [comment]
it's the real issue and the behavior is not accordance with RAML
event is not totally immutable.  event contains some field for marking.
the immutable one is reading value.  Please reopen this issue.

**Comment by cloudxxx8** [comment]
If the Event will be changed to immutable, the fields like modified and pushed should be removed as well as all the update API

**Comment by jduranf** [comment]
@tsconn23 I think it's very important to know if an event have been pushed or not. If an event haven't been pushed (maybe there is a connectivity error), then can be requested later. Also we have the Pushed attribute in the Event structure, which is used for this purpose, and there are several functions in core-data, defined in the RAML and already implemented (PUT in `api/v1/event/id/{id}` or DELETE in `api/v1/event/scrub`) , which handle the Pushed attribute.

I agree an Event it's immutable, and currently there is no way no modify it, except the pushed attribute, which happens later.

**Comment by cloudxxx8** [comment]
@tsconn23 , we are not asking to add a new feature to mark the pushed timestamp via REST API.  This is the current design, and this API exists right now with defect.  We are asking to fix the defect of this API.  Core WG could discuss whether we should remove this API and other event update API in the next API version, such as /api/v2/...., but we had better make the current and existing API work properly.

**Comment by tsconn23** [comment]
Changes have been requested on PR #370. Re-opening issue until PR is merged.

**Comment by jduranf** [comment]
Only event pushed time is updated via PUT in /api/v1/event/id/{id}.
Closing the issue as this have been fixed in #370

**Comment by cloudxxx8** [comment]
@jduranf @tsconn23  please noticed that #370 fixed another issue, not this one.  the pushed field readings belonging to the event will still not be updated.  do you need me to fix it or just treat this issue as not-fix-issue, and the pushed field of reading object will be always null.

**Comment by jduranf** [comment]
@cloudxxx8 I agree #370 didn't fix this issue, only it's related.
As have been said by @davidmsh, there is no really need to update the readings pushed time, and I think this issue was created only to comment if there is a really need to do such thing or not. And I think there is no real need.
Anyway, if you think there is a real need to implement such modification, we can reopen this issue.
